# Generated by Django 4.2.7 on 2025-10-18 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_cart_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='task',
            new_name='tax',
        ),
    ]
