# Generated by Django 4.2.7 on 2025-10-18 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_task_cart_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='tax',
            new_name='tax_fee',
        ),
    ]
