# Generated by Django 4.2.7 on 2025-10-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_tax_cart_tax_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorderitem',
            old_name='task_fee',
            new_name='price',
        ),
        migrations.AddField(
            model_name='cartorderitem',
            name='tax_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
