# Generated by Django 4.2.7 on 2025-10-18 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_task_fee_cartorderitem_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='teachers',
            new_name='teacher',
        ),
    ]
