# Generated by Django 4.2.7 on 2025-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_variantitem_description_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
