# Generated by Django 4.2.7 on 2025-10-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_variantitem_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='task_fee',
            new_name='tax_fee',
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='course-file'),
        ),
    ]
