# Generated by Django 4.2.7 on 2025-11-14 13:05

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_task_fee_cartorder_tax_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_answer',
            name='qa_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='123456789', length=6, max_length=20, prefix=''),
        ),
    ]
